### ISSUE TITLE
1.20 crash when looking up a item in jei

### ISSUE THREAD

**Issue by SDUBZ** [Lemon-Juiced/ScalarUtils5#1]
Forge: 46.0.14
Minecraft: 1.20
jei: jei-1.20-forge-14.0.0.11
scalarutils: scalar_utils-1.20-5.4.0.jar

[crash-2023-06-15_01.30.31-client.txt](https://github.com/Lemon-Juiced/ScalarUtils5/files/11763570/crash-2023-06-15_01.30.31-client.txt)

**Comment by Lemon-Juiced** [comment]
This seems to be a problem on JEI's side from what the crash report is showing me. I'm also not able to replicate it as I do not know what you've done to create the crash. There's an updated version for 1.20.1 that I would recommend moving to as soon as possible regardless.

**Comment by SDUBZ** [comment]
i think i made it work with emi since anytime it would show the recipe or goto it would just crash

**Comment by Lemon-Juiced** [comment]
Is it just Scalar Utils recipes, or is it recipes in general? What I can say for sure is that JEI 14.0.0.5 does work with the mod as that is what I tested it with. The recipes themselves shouldn't change at all because it is a vanilla feature. So it's likely JEI or even possibly Forge itself.
