### ISSUE TITLE
[1.20.1] Obsidian became unminable post necronite rework

### ISSUE THREAD

**Issue by Zedrimar** [Lemon-Juiced/ScalarUtils5#3]
It took an insanely long time for me to find this, but apparently in updating the necronite tier, obsidian was made unminable (at least by diamond and netherite pickaxes). pickaxes with higher mining level work just fine though. It has to be a mining level higher than netherite though. :/

tested with:
Forge (1.20.1) 47.1.3 
Scalar utils 5.4.16
Lemon Core 1.0.31

Probably useless, but link to log output anyway: https://pastebin.com/qbbmEt8N

**Comment by Lemon-Juiced** [comment]
I will look into this tonight when I get home from work.

**Comment by Lemon-Juiced** [comment]
I'm looking into it as I have some free time right now: line 25 in Mod Tiers might be the issue: https://github.com/Lemon-Juiced/ScalarUtils5/blob/2b94438f52be62ad62a0a4bc141ce6aeea52789f/src/main/java/lemon_juice/scalar_utils/item/custom/tiers/ModTiers.java#L25

I think I need to add a tag for Necronite instead of using both the diamond and netherite ones

**Comment by Lemon-Juiced** [comment]
I can't test it right now, but if my hypothesis is correct, this should be affecting all blocks that are mineable by diamond tier, but not below. So mainly crying obsidian, ancient debris, netherite blocks.

**Comment by Zedrimar** [comment]
Yeah I think you're right on that. Those are the only blocks I saw having any issues with. Thankfully I happen to have mods adding higher tier pickaxes so I can bypass for now, but yeah, those blocks you mentioned were the only ones I saw affected. Everything else I could mine just fine.

**Comment by Lemon-Juiced** [comment]
Okay then it should be fixed tonight, ill either set necronite back to what it was before the update or see if adding the tag fixes it.

**Comment by Lemon-Juiced** [comment]
This was tested and seems to have fixed the issue. Thank you very much for finding this.
