### ISSUE TITLE
[1.20.1] Pickaxe Minables became Unminable

### ISSUE THREAD

**Issue by Zedrimar** [Lemon-Juiced/ScalarUtils5#4]
I think there may have been an issue with tags post redundancy cleanup. Anything that would normally require a pickaxe to mine are now unable to be broken. This includes everything from stone, all the way up to netherite, with no tool tags assigned to any of them. Anything requiring other tools (hoe, axe, shovel) are unaffected. Previous version of scalar utils (5.4.18.0) works as intended.

Forge: 47.1.3
Scalar Utils: 5.4.18.1
Lemon Core: 1.0.31

Not sure if you need the log still, but to be on the safe side, here is the link to it:
https://pastebin.com/e3kUb8S8

And debug log just in case:
https://pastebin.com/dgCWM3J3

![image](https://github.com/Lemon-Juiced/ScalarUtils5/assets/8153290/8b1e002c-4eed-4aa0-8275-f18097915227)

**Comment by Lemon-Juiced** [comment]
See thats why it's a beta, there still a lot changing in this update and it's not completed yet. So the beta is up just to test the runeshifters. I probably should have labeled it alpha.

Itll be fixed today, im pretty sure I know what the issue is without even being at my computer.

**Comment by Lemon-Juiced** [comment]
This commit should have fixed the issue. I still have a few more changes I want to implement before uploading the release version of 5.4.18.

**Comment by Lemon-Juiced** [comment]
New version is released. This is all patched in the new release.

**Comment by Lemon-Juiced** [comment]
I've decided to officially credit Zedrimar as a tester on the CF page for having found multiple issues so far.

**Comment by Zedrimar** [comment]
That's fair, I wasn't expecting things to be perfect. I just figured I'd give you a heads up. I apologize If I ever come off as a bit rash. I'm autistic and not the greatest with communication. I'm doing my best to improve! :)

Also, thank you! If you ever have any builds in need of testing, I'd be happy to go through them and see if I can find anything! I am also currently trying to further my programming (and modding) knowledge, so I enjoy doing this. I plan on making a mod of my own one of these days. 

Is there anything I should keep in mind for bug reporting on alpha and beta builds?? I don't want to bug you with needless bug reports if it's already known ahead of time. Also, if you prefer I report bugs in a different format and or in a different location for said builds, let me know. I'll do whatever makes it easier for you. ^-^

**Comment by Lemon-Juiced** [comment]
You didn't give off any vibes like that at all. I have never been clinically tested but am likely also on the spectrum. 

As of right now I don't have much of anything, I am currently looking into a new feature here but its far from complete. I just tend to mess up the JSON for pickaxe blocks a lot by leaving old code in it. Also feel free to look through my source code if you want (its licensed such that anyone can really take what they need if they need it). I'll also help where I can.

Just keep reporting them as you have, you're doing a great job as is. Unless you'd prefer getting them to me a seperate way yourself.

**Comment by Zedrimar** [comment]
Ok cool, just wanted to make sure. And yeah, I've been taking a look every once in a while when commits are published just to get a feel for how it's set up. Forge has changed so much over the years, and now many are switching over to neoforge due to issues with the forge project manager. It's a bit difficult sometimes to keep up with all the new changes. :/ 

I swear, it feels like there's 50 different mod loaders now. It's cool and all, though it has become more difficult to tell which one is best to stick to. They all have their own benefits and downsides, though forge is still currently the most popular (at least for now). Some mod loaders are still so new that some launchers don't even have support for them yet as far as updating mods and even instance management. I really would prefer not to have to go back to the times of release 1.5 where all mods had to be searched for and updated manually every time. It's especially a pain for someone like me with an overkill mod list of over 400 mods. Updating that manually would be.... painful...

Honestly, the only thing I wonder at this point is just where to go to learn Java first. Sadly, university didn't teach Java, it was just C++, C and javascript for web development. I only have a really basic knowledge on java specifically as of right now. I need to go search youtube. Hopefully at least a few channels have relatively up to date videos for it. Hopefully I can at least gleen something from there before youtube eventually dies in a fiery blaze, especially considering the current rate of things.

Also, thank you! I just figured I'd ask, because I know some devs prefer things sent on their discord channels or CF. People get busy, and I get that it can sometimes be difficult to keep up on everything. Especially since modding is often just a hobby project for most, and life can get in the way of things. Unless they're one of the lucky few who can continue modding full time and survive just on donations alone. I personally prefer github, so unless things change and you ask bugs to be reported elsewhere, I'll continue reporting here. ^-^

**Comment by Lemon-Juiced** [comment]
My project is a mess. It's good for my organization, but every time I try to reorganize it I feel it gets worse. On the bright side their hasn't been super big major changes for the past few versions. For the most part it looks like both modloaders and Mojang are trying to keep things consistent so mods can just make the jump for the most part.

So it looks like that's going to change as NeoForge is basically just the old forge team minus a bad apple. I'm hoping the launchers start supporting NeoForge here soon as its actually been holding me back actively. Quilt and Fabric are also around, but from what I understand Quilt and Fabric are basically the same and are bound to cannibalize eachother.

Lucky for you C++ and Java are very similar. As long as you have a good understanding of OOP, Java should be easy to learn. However, sometimes you'll wonder why Mojang didn't use some basic OOP principles in parts of the game.

**Comment by Zedrimar** [comment]
It may be a mess, but it's a fun mess to play with! :D I feel you though. Coding is one of those things that either things work insanely well post re-structure, or... everything breaks.... Like, everything... Or at least that's how it can feel like sometimes, even if it's just something simple. Good to know at least with modding, things have been fairly consistent lately. 

At least it's Java and not something like Python, which while some find it easier, one misplaced space could literally stop everything from working. I much prefer having my semicolons and curly brackets lol. I felt like I went through the coding version of the vietnam war after having to learn python... There were many... Many days where programs broke from one errant space left somewhere by accident. Curse you non-whitespace spaces! I'd rather eat my hat before going through using python again. Anyway, sorry for the random side tangent.

Yeah I see (original) forge basically already stopped updating essentially, and everyone seems to be just holding out until neoforge gets launcher support. And of course, at least from what I heard, CF had changed their API so mods can't be updated on other launchers like multiMC, which honestly kinda sucks. The curseforge launcher is a buggy mess, but it's the only thing I know of right now that offers easy mod installation and updating. If you know of anything better, I'd love to hear it. I think at this point I may just look to getting mod updates from modrinth instead whenever possible.

I honestly don't even know how I feel about fabric or quilt. There's some really cool mods, but some of the devs seem to be so hellbent on staying with those mod loaders that they outright refuse to support anything else. It has created a bit of a divide. :/ Sure, there's still some ports of fabric mods, but it can be a toss up of how well those are able to be updated. I would love to see mods like "BetterEnd" to be fully supported on forge (and eventually neoforge) by the original creators.

Thankfully as far as OOP, I understand it pretty well so the learning part isn't that hard. I just need to find up to date learning guides and then find a relatively up to date modding guide. I'm not at all surprised though that Mojang's way of doing things can be a bit of a mess.
