### ISSUE TITLE
[1.20.1] Angel Ring No Longer Stops Fall Damage After Crossing Dimensions

### ISSUE THREAD

**Issue by Zedrimar** [Lemon-Juiced/ScalarUtils5#5]
I am so so sorry.... I found another bug! Angel ring works (super super nice), but.... After crossing dimensions, the check to stop fall damage fails. In short, your next landing will result in broken (thankfully only digital) legs. This is reset on re-equipping the angel ring until the next interdimensional journey.

forge 47.1.3
Scalar utils 5.4.18.3
lemon core 1.0.31

Debug: https://pastebin.com/7czTcgLT
Latest: https://pastebin.com/WzicZj5f

I didn't find anything in there, but sending here anyway just in case.

**Comment by Lemon-Juiced** [comment]
I will look into this. I saw similar posts on CF without any details and couldn't replicate. Not sure what would be causing this. Worse case ill look into other angel rings and see what they are doing.

**Comment by Zedrimar** [comment]
I wouldn't be surprised if it's a forge bug. Maybe trick the system into thinking it got re-equipped? I know earlier there was a weird bug with the angel ring being completely useless until re-equipped when crossing dimensions (which got fixed). Maybe it's something related to that?

Maybe it's attributes or something like that resetting? I know there's also an issue where the xp bar won't update when crossing dimensions until another xp point is gathered. There's a mod that fixes that thankfully. I think that may be related.

**Comment by Lemon-Juiced** [comment]
This is still being looked into. I'm not 100% certain of how this can be resolved yet.
Currently thinking about adding a check whenever the player takes fall damage to see if they have a ring and then stopping it OR checking if a player has a ring when changing dimensions and then reapplying all effects of it.

**Comment by Zedrimar** [comment]
Something I forgot to add earlier, but the game for whatever reason is acting like i'm always falling when changing dimensions. Traveling through a portal once, the flight ability works, but the game seems to think I am meant to be falling. If I take damage while in mid air (after one portal travel), it's also like the game is "correcting" my position and sends me straight to the ground. Or at the very least, several blocks lower than where I was before if I am up higher. I also found that if traveling through a portal twice without re-equipping the ring, the ring's abilities are completely useless until it is re-equipped. After the second travel, nothing will work at all after that.

I did also check if it's affected by teleporting just to make sure (using waystones mod). It seems to work fine so long as the teleport is in the same dimension. If at any point the active dimension is changed, forge seems to forget what abilities and attributes should be active (except when mods add a check to re-add abilities and what not). 

Oh, and it also sometimes decides to somewhat break again like after traveling dimensions if the game is reloaded. Weird...

I think you may need to go with the second option and re-apply the abilities on dimension switch. Not sure if it helps, but I was looking through here too: https://github.com/HybridAvenger69/Masstech-Angel-Ring/blob/main/1.20/src/main/java/com/hybridavenger69/mtar/compat/CuriosCompat.java. I don't know much of what is going on here, but it seems like there's a tick method under curios compat to check if the angel ring is equipped and let the player fly if equipped. That constant check might be how that mod gets around whatever forge is doing and forgetting active abilities. Been using that mod lately for the time being until this weirdness is dealt with.

**Comment by Zedrimar** [comment]
I did also check if it's affected by teleporting just to make sure (using waystones mod). It seems to work fine so long as the teleport is in the same dimension. If at any point the active dimension is changed, forge seems to forget what abilities and attributes should be active (except when mods add a check to re-add abilities and what not).

**Comment by Lemon-Juiced** [comment]
I'm not 100% what of that code can be applied to mine, but I have been looking into resolving this issue on and off. It has not fallen on deaf ears. However, I think that this bug may be linked to a bug in the main game that seems to be getting resolved in 1.20.3. I'm still not 100% certain of that, but I am still trying to resolve the issue.

**Comment by Lemon-Juiced** [comment]
Within minutes after posting that I found the solution... it works for me so I'm going to close this for now, if it comes back we can reopen.
